services:
  - type: web
    name: ai-study-buddy-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 